version: "3.9"

volumes:
  db_vol: # data volume for mysql
  redis_vol: # data volume for redis
  media_vol: # data volume for django media, the user upload files
  static_vol: # data volume for django static

networks: # Customised network (default bridge), no links communication
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf # Start the redis server after the container starts
    networks:
      - redis_network
    volumes:
      - redis_vol:/data # Backup to redis data via mount redis_vol
      - ./compose/redis/redis.conf:/etc/redis/redis.conf # Mount redis config file
    ports:
      - "6379:6379"
    restart: always # this means always restart when the container runs with a error

  db:
    image: mysql
    env_file:
      - ./myproject/.env # use .env file for environment variables
    networks:
      - db_network
    volumes:
      - db_vol:/var/lib/mysql:rw # Mount database data, readable and writable
      - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf # Mount config file
      - ./compose/mysql/init:/docker-entrypoint-initdb.d/ # Mount sql initialise script
    ports:
      - "3306:3306" # Consistency with config file
    restart: always

  web:
    build: ./myproject
    expose:
      - "8000"
    volumes:
      - ./myproject:/var/www/html/myproject # Mount project code
      - static_vol:/var/www/html/myproject/static # Mount static path to static_vol
      - media_vol:/var/www/html/myproject/media # Mount media path to media_vol
      - ./compose/uwsgi:/tmp # Mount uwsgi log (For viewing Django's logs at runtime)
    networks:
      - nginx_network
      - db_network
      - redis_network
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    build: ./compose/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf # Mount nginx config file
      - ./compose/nginx/ssl:/usr/share/nginx/ssl # Mount ssl certificates path
      - ./compose/nginx/log:/var/log/nginx # Mount log
      - static_vol:/usr/share/nginx/html/static # Mount static file to static_vol
      - media_vol:/usr/share/nginx/html/media # Mount media file to media_vol
    networks:
      - nginx_network
    depends_on:
      - web
    restart: always