name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: SSH Setup
          uses: webfactory/ssh-agent@v0.5.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Update code on server
          run: |
            ssh USER@SERVER_IP_ADDRESS "cd /path/to/project && git pull && sh deploy.sh"
          env:
            SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
